mongo:
  image: mongo:latest

postgres:
  image: openmhealth/omh-postgres:latest

authorization:
  image: openmhealth/omh-dsu-authorization-server:latest
  links:
    - mongo:omh-mongo
    - postgres:omh-postgres
  ports:
    - "8085:8082"

resource:
  image: openmhealth/omh-dsu-resource-server:latest
  links:
    - mongo:omh-mongo
    - postgres:omh-postgres
  ports:
    - "8086:8083"
